// --- UPDATE THESE TWO VARIABLES ---
const REPO_OWNER = "Reshma-Thouti";
const REPO_NAME = "Leet_GFG_solutions";
// ----------------------------------

function utf8ToBase64(str) {
    return btoa(unescape(encodeURIComponent(str)));
}

async function uploadFileToGitHub(token, path, content, commitMessage) {
    const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}`;
    const encodedContent = utf8ToBase64(content);
    let sha = null;

    try {
        const getResponse = await fetch(url, {
            headers: { 'Authorization': `Bearer ${token}`, 'Accept': 'application/vnd.github.v3+json' },
            cache: 'no-store'
        });
        if (getResponse.ok) {
            const fileData = await getResponse.json();
            sha = fileData.sha;
        }
    } catch (e) {}

    try {
        const body = { message: commitMessage, content: encodedContent };
        if (sha) body.sha = sha;

        const response = await fetch(url, {
            method: 'PUT',
            headers: {
                'Authorization': `Bearer ${token}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(body)
        });

        if (response.ok) {
            console.log(`LeetSync: Successfully pushed -> ${path}`);
            return true;
        } else {
            console.error("LeetSync: Failed to push");
            return false;
        }
    } catch (error) {
        console.error("LeetSync: Network error", error);
        return false;
    }
}

async function getDefaultBranch(token) {
    const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}`;
    try {
        const response = await fetch(url, { headers: { 'Authorization': `Bearer ${token}` }, cache: 'no-store' });
        const data = await response.json();
        return data.default_branch || "main";
    } catch (e) { return "main"; }
}

async function generateMasterReadme(token, platform, language) {
    await new Promise(resolve => setTimeout(resolve, 2000));
    const branch = await getDefaultBranch(token);
    const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/git/trees/${branch}?recursive=1`;

    try {
        const response = await fetch(url, { headers: { 'Authorization': `Bearer ${token}`, 'Accept': 'application/vnd.github.v3+json' }, cache: 'no-store' });
        if (!response.ok) return;
        const data = await response.json();

        let easy = 0, medium = 0, hard = 0;

        data.tree.forEach(item => {
            if (item.path.startsWith(`${platform}/${language}/`) && item.path.endsWith('README.md') && item.path.split('/').length > 3) {
                if (item.path.includes('/Easy/')) easy++;
                if (item.path.includes('/Medium/')) medium++;
                if (item.path.includes('/Hard/')) hard++;
            }
        });

        const total = easy + medium + hard;
        const masterContent = `# ☕ ${language} Problem Solving Portfolio\n\n` +
            `Welcome to my ${language} solutions for **${platform}**. This repository is automatically synced using LeetSync.\n\n` +
            `### 📊 Live Stats\n` +
            `![Total](https://img.shields.io/badge/Total_Solved-${total}-blue) ` +
            `![Easy](https://img.shields.io/badge/Easy-${easy}-brightgreen) ` +
            `![Medium](https://img.shields.io/badge/Medium-${medium}-orange) ` +
            `![Hard](https://img.shields.io/badge/Hard-${hard}-red)\n\n` +
            `---\n*Auto-generated by LeetSync*`;

        const masterPath = `${platform}/${language}/README.md`;
        await uploadFileToGitHub(token, masterPath, masterContent, `Update ${platform} ${language} Master Dashboard`);
    } catch (error) { console.error(error); }
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "SUBMISSION_ACCEPTED") {
        const data = message.payload;

        // Pulling all the streak data from storage
        chrome.storage.local.get(["githubToken", "syncCount", "recentSyncs", "currentStreak", "maxStreak", "lastActiveDate"], async (result) => {
            const token = result.githubToken;
            let currentCount = result.syncCount || 0;
            let recentSyncs = result.recentSyncs || [];

            // Streak Variables
            let currentStreak = result.currentStreak || 0;
            let maxStreak = result.maxStreak || 0;
            let lastActiveDate = result.lastActiveDate || null;

            if (!token) return;

            const folderName = data.title.replace(/[^a-zA-Z0-9 \-]/g, "").trim();
            const codePath = `${data.platform}/${data.languageFolder}/${data.difficulty}/${folderName}/Solution${data.fileExtension}`;
            const readmePath = `${data.platform}/${data.languageFolder}/${data.difficulty}/${folderName}/README.md`;

            // 1. Upload Code & Readme
            await uploadFileToGitHub(token, codePath, data.code, `Add ${data.difficulty} ${data.languageFolder} Solution from ${data.platform}`);
            let diffColor = "lightgrey";
            if (["Easy", "Basic", "School"].includes(data.difficulty)) diffColor = "brightgreen";
            if (data.difficulty === "Medium") diffColor = "orange";
            if (data.difficulty === "Hard") diffColor = "red";

            const readmeContent = `# 📝 ${data.title} (${data.platform})\n\n🔗 [Problem Link](${data.problemUrl})\n\n![Difficulty](https://img.shields.io/badge/Difficulty-${data.difficulty}-${diffColor}) ![Language](https://img.shields.io/badge/Language-${data.languageFolder}-blue)\n\n### 💡 Tags\n${data.tags}\n\n### 🚀 Performance\n- **Runtime:** ${data.runtime}\n- **Memory:** ${data.memory}\n\n---\n\n### 📜 Problem Description\n${data.description}`;
            await uploadFileToGitHub(token, readmePath, readmeContent, `Add README for ${data.title}`);

            // 2. Update Master Dashboard
            await generateMasterReadme(token, data.platform, data.languageFolder);

            // 3. Streak Algorithm
            const todayISO = new Date();
            // Create a Local YYYY-MM-DD string to prevent timezone hopping bugs
            const todayStr = todayISO.toLocaleDateString('en-CA');

            if (lastActiveDate !== todayStr) {
                if (lastActiveDate) {
                    const lastDate = new Date(lastActiveDate);
                    const currentDate = new Date(todayStr);
                    const diffTime = Math.abs(currentDate - lastDate);
                    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

                    if (diffDays === 1) {
                        currentStreak++; // Next consecutive day!
                    } else if (diffDays > 1) {
                        currentStreak = 1; // Streak broken, reset to 1
                    }
                } else {
                    currentStreak = 1; // First problem ever solved
                }

                if (currentStreak > maxStreak) maxStreak = currentStreak;
                lastActiveDate = todayStr;
            }

            // 4. Update Audit Log
            currentCount++;
            const githubUrl = `https://github.com/${REPO_OWNER}/${REPO_NAME}/tree/main/${data.platform}/${data.languageFolder}/${data.difficulty}/${folderName}`;

            recentSyncs.unshift({
                title: data.title,
                difficulty: data.difficulty,
                platform: data.platform,
                url: githubUrl,
                timestamp: todayISO.toISOString() // Saves exact time for the "2m ago" UI
            });
            if (recentSyncs.length > 5) recentSyncs.pop();

            // Save everything back to Chrome Storage
            chrome.storage.local.set({
                syncCount: currentCount,
                recentSyncs: recentSyncs,
                currentStreak: currentStreak,
                maxStreak: maxStreak,
                lastActiveDate: lastActiveDate
            });
        });
    }
});

// Securely bypass DOM Virtualization to grab the full Monaco Editor code
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "GET_FULL_CODE") {
        console.log("LeetSync Background: Attempting to extract full code from MAIN world...");

        chrome.scripting.executeScript({
            target: { tabId: sender.tab.id },
            world: "MAIN", // Bypasses Chrome Extension isolation to read LeetCode's variables
            func: () => {
                try {
                    // Attempt 1: Native Monaco Editor API
                    if (window.monaco && window.monaco.editor) {
                        const models = window.monaco.editor.getModels();
                        if (models.length > 0) return models[0].getValue();
                    }

                    // Attempt 2: React Fiber Tree Traversal
                    let extractedCode = null;
                    const editorNodes = document.querySelectorAll('.monaco-editor, .react-codemirror2');
                    for (let el of editorNodes) {
                        const reactKey = Object.keys(el).find(k => k.startsWith('__reactFiber$'));
                        if (reactKey) {
                            let node = el[reactKey];
                            while (node) {
                                if (node.memoizedProps && node.memoizedProps.value) {
                                    extractedCode = node.memoizedProps.value;
                                    break;
                                }
                                node = node.return;
                            }
                        }
                        if (extractedCode) break;
                    }
                    return extractedCode;
                } catch (e) {
                    return null;
                }
            }
        }).then(results => {
            sendResponse({ code: results[0].result });
        }).catch(err => {
            console.error("Script injection failed:", err);
            sendResponse({ code: null });
        });

        return true; // Tells Chrome we will send the response asynchronously
    }
});